### ISSUE TITLE
trabalho-01

### ISSUE THREAD

**Issue by fsantanna** [TiagoRezende/EDL#1]
O texto está bem escrito.
- Comentários (sobre o exemplo):
  - explicar porque escolheu o exemplo e comentar sobre o código
  - verificar a formatação do código

**Comment by fsantanna** [comment]
A formatação do código continua quebrada (`override func <...>` está fora do retângulo).
Quando pedi para explicar a escolha do exemplo, queria que você explicasse por que esse código é representativo da linguagem. O que tem no código que distingue Swift de outras linguagens? (Por exemplo, em termos dos critérios que você mencionou no parágrafo anterior.)

**Comment by TiagoRezende** [comment]
Já consertei, esta tudo ok agora?

Em 19 de março de 2016 12:22, fsantanna notifications@github.com escreveu:
